### ISSUE TITLE
color formatter/AP documentation/implementation errors

### ISSUE THREAD

**Issue by jtara** [rocketjob/semantic_logger#131]
### Environment

* Ruby Version : 2.5.0
* Semantic Logger Version: 4.4.0
* Awesome Print Version: 1.8.0
* Application/framework names: sinatra 2.0.5

### Expected Behavior

1. `~/.aprc` content should override AwesomePrint configuration
2. It should be possible to pass color formatter options using *SemanticLogger.add_appender()*
3. Documentation on how to do this should be found in main documentation, not by searching through code.

### Actual Behavior

1. `~.aprc` content does not affect AwesomePrint configuration
2. Passing color formatter options as shown in in-code documentation throws an error.
3. Documentation only found in code (`color.rb`) but doesn't work as shown in any case.

### Workaround

I wish to use *multiline: true*.  I locally patch `color.rb` with *multiline:true*.

#### In-code documentation:

``` ruby
      # Adds color to the default log formatter
      #
      # Example:
      #   # Use a colorized output logger.
      #   SemanticLogger.add_appender(io: $stdout, formatter: :color)
      #
      # Example:
      #   # Use a colorized output logger chenging the color for info to green.
      #   SemanticLogger.add_appender(io: $stdout, formatter: :color, color_map: {info: SemanticLogger::AnsiColors::YELLOW})
      #
      # Parameters:
      #  ap: [Hash]
      #    Any valid AwesomePrint option for rendering data.
      #    These options can also be changed be creating a `~/.aprc` file.
      #    See: https://github.com/michaeldv/awesome_print
      #
      #    Note: The option :multiline is set to false if not supplied.
      #    Note: Has no effect if Awesome Print is not installed.
      #
      #  color_map: [Hash | SemanticLogger::Formatters::Color::ColorMap]
      #    ColorMaps each of the log levels to a color
```

#### comments on in-code documentation:

1. Minor error: "changing" misspelled
2. Minor error: "it says the code changes the info color to green. It changes it to yellow.
3. The given example throws an error.
4. Modifying the given example to make the AP change I want throws an error.

#### Trace output

I've included trace output for the example supplied in the in-code documentation. I get a similar output for my desired configuration.

``` ruby
SemanticLogger.add_appender(io: $stdout, formatter: :color, color_map: {info: SemanticLogger::AnsiColors::YELLOW})
```

```
➜  server git:(93-logging) ✗ rake run --trace
** Invoke run (first_time)
** Execute run
bundle exec rackup config.ru -p 4444
Traceback (most recent call last):
	24: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/ruby_executable_hooks:24:in `<main>'
	23: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/ruby_executable_hooks:24:in `eval'
	22: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/rackup:23:in `<main>'
	21: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/rackup:23:in `load'
	20: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	19: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	18: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
	17: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	16: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	15: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	14: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	13: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	12: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	11: from /Users/jon/workspace/spatvis-api/server/config.ru:in `<main>'
	10: from /Users/jon/workspace/spatvis-api/server/config.ru:in `new'
	 9: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	 8: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	 7: from /Users/jon/workspace/spatvis-api/server/config.ru:38:in `block in <main>'
	 6: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/semantic_logger.rb:155:in `add_appender'
	 5: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/appenders.rb:13:in `add'
	 4: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/appender.rb:49:in `factory'
	 3: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/appender.rb:72:in `build'
	 2: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/appender.rb:72:in `new'
	 1: from /Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/appender/file.rb:71:in `initialize'
/Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/gems/semantic_logger-4.4.0/lib/semantic_logger/subscriber.rb:95:in `initialize': unknown keyword: color_map (ArgumentError)
rake aborted!
Command failed with status (1): [bundle exec rackup config.ru -p 4444...]
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:57:in `sh'
/Users/jon/workspace/spatvis-api/server/Rakefile:8:in `block in <top (required)>'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/jon/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/jon/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/jon/.rvm/gems/ruby-2.5.0@global/bin/rake:23:in `load'
/Users/jon/.rvm/gems/ruby-2.5.0@global/bin/rake:23:in `<main>'
/Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/ruby_executable_hooks:24:in `eval'
/Users/jon/.rvm/gems/ruby-2.5.0@sal_2_0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => run
```

**Comment by reidmorrison** [comment]
This option is documented as part of the Rails Semantic Logger documentation, it would not be hard for you to submit a pull request with this documentation customized for Semantic Logger:

**Comment by jtara** [comment]
I'm afraid I haven't been able to get any of the above suggestions to actually work.

I continue to just patch the Gem...

**Comment by jtara** [comment]
The issue really is in my usage of https://github.com/minodes/sinatra-logger

I needed to included the formatter and options in the Sinatra logger initialization.

sinatra-logger deletes appenders and provides it's own.

https://github.com/minodes/sinatra-logger

This works:

``` ruby
class BaseController < Sinatra::Base

  logger(
    filename: '/dev/stdout',
    formatter: {color: {ap: {multiline: true}}},
    level: ENV['LOG_LEVEL'],
    )

...
```

I will pull together a documentation update based on the Rails Semantic Logger documentation, and also write something up for sinatra-logger. I think it's also worth mentioning sinatra-logger in the docs here, as the standard way will not work since sinatra-logger will just remove the appender and replace with it's own.
