### ISSUE TITLE
Exception: NoMethodError: undefined method `message' for nil:NilClass

### ISSUE THREAD

**Issue by thg303** [rocketjob/semantic_logger#140]
### Environment
* Ruby Version: 2.5
* Semantic Logger Version: 4.5.0
* Application/framework: Rails 5.1.6
* Rails Semantic Logger Version: 4.4.2
* Rails configuration: 
# initializer/graylog.rb
SemanticLogger.add_appender(
  appender: :graylog,
  url: Rails.env.production? ? 'udp://<ip>:12201' : 'tcp://<ip>:12201'
)
# environments/development.rb
config.rails_semantic_logger.add_file_appender = false
  config.semantic_logger.add_appender(io: STDOUT, level: config.log_level, formatter: config.rails_semantic_logger.format)

* Full Stack Trace, if an exception is being raised.
```
rails db:drop
I, [2019-09-28T13:36:31.552725 #24089]  INFO -- sentry: ** [Raven] Raven 2.9.0 ready to catch errors
2019-09-28 13:36:32.001152 I [24089:47433506317960] Rails -- Raven 2.9.0 configured not to capture errors: Not configured to send/capture in environment 'default'
2019-09-28 13:36:32.003069 D [24089:47433506317960] Sidekiq -- Sidekiq client with redis options {:url=>"redis://localhost:6379/12", :id=>"Sidekiq-client-PID-24089"}
2019-09-28 13:36:32.044983 W [24089:47433506317960] Rails -- DEPRECATION WARNING: Active Admin: The `register_stylesheet` config is deprecated and will be removed
in v2. Import your "active_admin/sortable.css" stylesheet in the active_admin.scss.
 (called from <top (required)> at /home/ali/projects/chamedoon/cham-back/config/environment.rb:5)
2019-09-28 13:36:32.045122 W [24089:47433506317960] Rails -- DEPRECATION WARNING: Active Admin: The `register_javascript` config is deprecated and will be removed
in v2. Import your "active_admin/sortable.js" javascript in the active_admin.js.
 (called from <top (required)> at /home/ali/projects/chamedoon/cham-back/config/environment.rb:5)
2019-09-28 13:36:32.303095 W [24089:47433506317960] FlightOrder -- Creating scope :system. Overwriting existing method FlightOrder.system.
Dropped database 'chamedoon_dev_db'
2019-09-28 13:36:32.581454 D [24089:47433506317960] (0.154ms) ActiveRecord -- {:sql=>"DROP DATABASE IF EXISTS \"chamedoon_dev_db\""}
2019-09-28 13:36:32.583041 E [24089:SemanticLogger::Appenders] SemanticLogger::Appenders -- Failed to log to appender: #<SemanticLogger::Appender::Graylog:0x00005647f8511fa8 @url="tcp://185.116.162.194:12201", @max_size="WAN", @gelf_options={:protocol=>1, :facility=>"Semantic Logger"}, @level_map=#<SemanticLogger::Appender::Graylog::LevelMap:0x00005647f8511ee0 @trace=0, @debug=0, @info=1, @warn=2, @error=3, @fatal=4>, @formatter=#<SemanticLogger::Appender::Graylog:0x00005647f8511fa8 ...>, @application=nil, @host=nil, @metrics=false, @filter=nil, @name="SemanticLogger::Appender::Graylog", @level_index=nil, @level=nil, @server="185.116.162.194", @port=12201, @protocol=:tcp, @notifier=#<GELF::Notifier:0x00005647f8511c60 @enabled=true, @collect_file_and_line=false, @random=#<Random:0x00005647f8511c38>, @level=0, @max_chunk_size=1420, @rescue_network_errors=false, @default_options={"protocol"=>1, "facility"=>"Semantic Logger", "version"=>"1.0", "host"=>"ali-SliverBullet", "level"=>5}, @level_mapping={0=>7, 1=>6, 2=>5, 3=>4, 4=>3, 5=>1}, @sender=#<GELF::Transport::TCP:0x00005647f85118a0 @sockets=[#<TCPSocket:fd 9, AF_INET, 192.168.11.119, 46350>], @addresses=[["185.116.162.194", 12201]]>>> -- Exception: NoMethodError: undefined method `message' for nil:NilClass
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/graylog.rb:121:in `call'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/graylog.rb:130:in `log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:21:in `block in log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:19:in `each'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:19:in `log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:150:in `process_messages'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:119:in `process'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:75:in `block in thread'
Dropped database 'chamedoon_test_db'
2019-09-28 13:36:32.596718 D [24089:47433506317960] (0.250ms) ActiveRecord -- {:sql=>"DROP DATABASE IF EXISTS \"chamedoon_test_db\""}
2019-09-28 13:36:32.598349 E [24089:SemanticLogger::Appenders] SemanticLogger::Appenders -- Failed to log to appender: #<SemanticLogger::Appender::Graylog:0x00005647f8511fa8 @url="tcp://185.116.162.194:12201", @max_size="WAN", @gelf_options={:protocol=>1, :facility=>"Semantic Logger"}, @level_map=#<SemanticLogger::Appender::Graylog::LevelMap:0x00005647f8511ee0 @trace=0, @debug=0, @info=1, @warn=2, @error=3, @fatal=4>, @formatter=#<SemanticLogger::Appender::Graylog:0x00005647f8511fa8 ...>, @application=nil, @host=nil, @metrics=false, @filter=nil, @name="SemanticLogger::Appender::Graylog", @level_index=nil, @level=nil, @server="185.116.162.194", @port=12201, @protocol=:tcp, @notifier=#<GELF::Notifier:0x00005647f8511c60 @enabled=true, @collect_file_and_line=false, @random=#<Random:0x00005647f8511c38>, @level=0, @max_chunk_size=1420, @rescue_network_errors=false, @default_options={"protocol"=>1, "facility"=>"Semantic Logger", "version"=>"1.0", "host"=>"ali-SliverBullet", "level"=>5}, @level_mapping={0=>7, 1=>6, 2=>5, 3=>4, 4=>3, 5=>1}, @sender=#<GELF::Transport::TCP:0x00005647f85118a0 @sockets=[#<TCPSocket:fd 9, AF_INET, 192.168.11.119, 46350>], @addresses=[["185.116.162.194", 12201]]>>> -- Exception: NoMethodError: undefined method `message' for nil:NilClass
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/graylog.rb:121:in `call'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/graylog.rb:130:in `log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:21:in `block in log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:19:in `each'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appenders.rb:19:in `log'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:150:in `process_messages'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:119:in `process'
/home/ali/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/semantic_logger-4.5.0/lib/semantic_logger/appender/async.rb:75:in `block in thread'
```

Note:
* If the issue is with extensions to Rails to make it use Semantic Logger, please report the issue at [Rails Semantic Logger](https://github.com/rocketjob/rails_semantic_logger/issues).
* All appender issues should be reported here.

### Expected Behavior

* Describe your expectation of how Semantic Logger should behave, perhaps by showing how the builtin Ruby logger behaves.
* Provide a standalone Ruby script or a link to an example repository that helps reproduce the issue.
it should report the log and does not throw any exception.

### Actual Behavior
it throws Exception: Exception: NoMethodError: undefined method `message' for nil:NilClass.
the stack trace is provided above.

### Pull Request
I could solve this exception by editing [this line ](https://github.com/rocketjob/semantic_logger/blob/0196730749a6912fbd177c099d76be17be901e0b/lib/semantic_logger/appender/graylog.rb#L121)
like this:
```
          h[:short_message] = h.delete(:message)
          if h[:short_message].nil?
             h[:short_message] = log.exception.nil?  ? '<no-exception-message>' : log.exception.message
          end
```
In my case, I found that the error message was in the "payload" part of the hash, but I don't think it's a good idea to stringify that part of the hash, since I don't think it would cover all situations. 
if that's good I can make the PR

**Comment by reidmorrison** [comment]
Thank you for the pull request :tada:
