### ISSUE TITLE
errors with semantic_logger and actioncable

### ISSUE THREAD

**Issue by gingerlime** [rocketjob/semantic_logger#145]
### Environment

Provide at least:
* Ruby Version 2.5.3
* Semantic Logger Version 4.6.0
* Rails 5.2
* Rails Semantic Logger Version 4.4.3

```
NoMethodError: undefined method `processor' for Class:Class: /
var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/logger.rb:78:in `rescue in block in call_subscribers'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/logger.rb:75:in `block in call_subscribers'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/logger.rb:74:in `each'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/logger.rb:74:in `call_subscribers'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/logger.rb:61:in `log'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/base.rb:323:in `log_internal'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/base.rb:84:in `error'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/actioncable-5.2.3/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `block in log'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/semantic_logger.rb:337:in `tagged'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.6.0/lib/semantic_logger/base.rb:199:in `tagged'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/rails_semantic_logger-4.4.3/lib/rails_semantic_logger/extensions/action_cable/tagged_logger_proxy.rb:8:in `tag'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/actioncable-5.2.3/lib/action_cable/connection/tagged_logger_proxy.rb:38:in `log'
/var/local/kenhub/kenhub.d/1203/vendor/bundle/ruby/2.5.0/gems/actioncable-5.2.3/lib/action_cable/connection/tagged_logger_proxy.rb:32:in `block (2 levels) in <class:TaggedLoggerProxy>'
...
```

### Expected Behavior

I'm doing an initial investigation, so not entirely sure, but the issue surfaced after introducing actioncable to our stack. It doesn't happen in development mode for some reason, but only on staging. I tried to mimic the semantic_logger config in my development environment, but still can't reproduce it there :-/ 

### Actual Behavior

* Somehow we're getting this error whenever the client connects to the server via websocket

I'll try to post more details when I have them, but thought I'd ask and see if anyone bumped into something similar before.

**Comment by gingerlime** [comment]
after digging a bit deeper, it's actually not related to actioncable, but it seems to stem from a change to Semantic Logger in 4.6.0 (it seems not to happen with 4.5.0)

I'll create a separate issue to describe it.
