### ISSUE TITLE
semantic logger is not working with complex filter defined as module.

### ISSUE THREAD

**Issue by harry43** [rocketjob/semantic_logger#162]
We have a complex filter to be used for filtering out the logs for some specific requests. 

For that we wanted to use a complex filter as **Module** as given in the test case:
https://github.com/rocketjob/semantic_logger/blob/fa439a3ed8ef0d4408d686a82f418e126b8ef734/test/logger_test.rb#L13-L17

But semantic logger is giving us error **filter must be a Regexp or Proc** on https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/base.rb:273. 

It's working fine with filter as **Proc** but as a **Module** it  doesn't work

### Environment
* ruby 2.7.2p137
* semantic_logger (4.7.2)
* Rails
* rails_semantic_logger (4.4.4)

### Expected Behavior

* semantic_logger should not raise error when a complex filter is used as Module as per the given test case:
https://github.com/rocketjob/semantic_logger/blob/fa439a3ed8ef0d4408d686a82f418e126b8ef734/test/logger_test.rb#L13-L17

### Actual Behavior
```
Traceback (most recent call last):
	83: from bin/rails:4:in `<main>'
	82: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	81: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	80: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	79: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	78: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	77: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	76: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	75: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	74: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
	73: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
	72: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
	71: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	70: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	69: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	68: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
	67: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'
	66: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	65: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:39:in `start'
	64: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	63: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	62: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	61: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	60: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	59: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	58: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	57: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	56: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	55: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	54: from config.ru:5:in `block in <main>'
	53: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	52: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
	51: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	50: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
	49: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
	48: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	47: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	46: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	45: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	44: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	43: from /Users/developer/Desktop/my_application/config/environment.rb:7:in `<main>'
	42: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
	41: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
	40: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	39: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	38: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	37: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	36: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	35: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	34: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	33: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	32: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
	31: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
	30: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	29: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	28: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	27: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	26: from /Users/developer/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	25: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	24: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
	23: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
	22: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
	21: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
	20: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
	19: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
	18: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
	17: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
	16: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
	15: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
	14: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
	13: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	12: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	11: from /Users/developer/Desktop/my_application/config/initializers/semantic_logger.rb:6:in `<main>'
	10: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/railtie.rb:216:in `configure'
	 9: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.4/lib/rails/railtie.rb:216:in `instance_eval'
	 8: from /Users/developer/Desktop/my_application/config/initializers/semantic_logger.rb:10:in `block in <main>'
	 7: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/semantic_logger.rb:167:in `add_appender'
	 6: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/appenders.rb:12:in `add'
	 5: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/appender.rb:32:in `factory'
	 4: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/appender.rb:60:in `build'
	 3: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/appender.rb:60:in `new'
	 2: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/appender/file.rb:72:in `initialize'
	 1: from /Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/subscriber.rb:110:in `initialize'
/Users/developer/.rvm/gems/ruby-2.7.2/gems/semantic_logger-4.7.2/lib/semantic_logger/base.rb:273:in `initialize': :filter must be a Regexp or Proc (RuntimeError)
```

**Comment by reidmorrison** [comment]
Semantic Logger v4.7.4 with the above fix has been published.

**Comment by harry43** [comment]
thanks @reidmorrison
