### ISSUE TITLE
log.to_h and log.to_json yield different results (3.2.1)

### ISSUE THREAD

**Issue by timuckun** [rocketjob/semantic_logger#24]
```ruby
pry(#<SemanticLogger::Log>):1> to_h
=> {:host=>"tims-mac.local",
 :application=>"Semantic Logger",
 :name=>"Rails",
 :pid=>16094,
 :thread=>"70245767569880",
 :time=>2016-04-11 14:13:50 +1200,
 :level=>:warn,
 :level_index=>3,
 :file=>"(irb)",
 :line=>3,
 :message=>"test"}
[37] pry(#<SemanticLogger::Log>):1> to_json
=> "{\"level\":\"warn\",\"thread_name\":\"70245767569880\",\"name\":\"Rails\",\"message\":\"test\",\"payload\":null,\"time\":\"2016-04-11T14:13:50.529+12:00\",\"duration\":null,\"tags\":[],\"level_index\":3,\"exception\":null,\"metric\":null,\"backtrace\":[\"(irb):3:in `irb_binding'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:623:in `signal_status'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:485:in `eval_input'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:395:in `block in start'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:394:in `catch'\",\"/Users/tim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/irb.rb:394:in `start'\",\"/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'\",\"/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'\",\"/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'\",\"/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'\",\"/Users/tim/.gem/ruby/2.2.3/gems/railties-4.2.5/lib/rails/commands.rb:17:in `\\u003ctop (required)\\u003e'\",\"bin/rails:4:in `require'\",\"bin/rails:4:in `\\u003cmain\\u003e'\"],\"metric_amount\":null}"
```

**Comment by timuckun** [comment]
Just read through the source code.  It looks like this is intended behaviour. Closing ticket although I like the struct format much better due to consistency.

**Comment by timuckun** [comment]
NOTE:  Metric amount is not in the to_h method

```ruby
log.to_h
=> {:name=>"Rails",
 :pid=>16402,
 :thread=>"SemanticLogger::AppenderThread",
 :time=>2016-04-11 15:23:29 +1200,
 :level=>:warn,
 :level_index=>3,
 :host=>"tims-mac.local",
 :application=>"Semantic Logger",
 :message=>"Purchase complete total amount",
 :metric=>"departments/clothing"}
[2] pry(#<DbAppender2>)> log
=> #<struct SemanticLogger::Log
 level=:warn,
 thread_name="SemanticLogger::AppenderThread",
 name="Rails",
 message="Purchase complete total amount",
 payload=nil,
 time=2016-04-11 15:23:29 +1200,
 duration=nil,
 tags=[],
 level_index=3,
 exception=nil,
 metric="departments/clothing",
 backtrace=nil,
 metric_amount=189.42>
```

**Comment by timuckun** [comment]
Note: duration_human says miliseconds when it means seconds.

```ruby
log.to_h
=> {:name=>"Rails",
 :pid=>16402,
 :thread=>"70296287961560",
 :time=>2016-04-11 15:31:58 +1200,
 :level=>:warn,
 :level_index=>3,
 :host=>"tims-mac.local",
 :application=>"Semantic Logger",
 :duration_ms=>1 second,
 :duration=>"1.000ms",
 :message=>"three minutes"}
```
