### ISSUE TITLE
Incompatible with honeybadger?

### ISSUE THREAD

**Issue by mhenrixon** [rocketjob/semantic_logger#53]
Adding semantic logger to an existing project yields the following result:

```
/Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/logging.rb:29:in `<': comparison of Fixnum with :debug failed (ArgumentError)
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/logging.rb:29:in `warn'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/agent.rb:124:in `initialize'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/agent.rb:69:in `new'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/agent.rb:69:in `start'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger.rb:30:in `start'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/honeybadger-2.7.2/lib/honeybadger/init/rails.rb:20:in `block in <class:Railtie>'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /Users/mhenrixon/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
  from /Users/mhenrixon/Code/project_name/config/environment.rb:5:in `<top (required)>'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mhenrixon/Code/project_name/config.ru:3:in `block in <main>'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
  from /Users/mhenrixon/Code/project_name/config.ru:in `new'
  from /Users/mhenrixon/Code/project_name/config.ru:in `<main>'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/server.rb:61:in `app'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/rack-1.6.5/lib/rack/server.rb:272:in `start'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/mhenrixon/.rvm/gems/ruby-2.3.1/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

Anyone have any ideas why that is happening?

**Comment by jalberto** [comment]
related to: https://github.com/rocketjob/semantic_logger/issues/28

**Comment by reidmorrison** [comment]
This should be fixed in v4.

Please re-open the ticket with further information, or post questions in the gitter support channel  if you are still experiencing difficulties.
