### ISSUE TITLE
Problem rails 5.1 and ruby 2.4.1

### ISSUE THREAD

**Issue by igortice** [rocketjob/semantic_logger#66]
E [18506:puma 005 log_subscriber.rb:85] ActiveRecord::Base -- Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 1, expected 2)

**Comment by reidmorrison** [comment]
We just tried Rails 5.1 with the latest Rails Semantic Logger and Semantic Logger gems and it works fine. Suggest upgrading to the latest.

**Comment by reidmorrison** [comment]
Give V4.1 a try. If you still see issues, please re-open this ticket along with a complete stack trace.

**Comment by raphaelpra** [comment]
Hello I am facing the same error.

Let me provide a little more details:
* rails 5.1.5
* rails_semantic_logger 4.2.0

```
Could not log "sql.active_record" event. ArgumentError: wrong number of arguments (given 2, expected 1) ["/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/log_subscriber.rb:45:in `type_casted_binds'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/active_record/log_subscriber.rb:33:in `sql'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/subscriber.rb:99:in `finish'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/log_subscriber.rb:83:in `finish'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:102:in `finish'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `block in finish'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `each'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/fanout.rb:46:in `finish'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:27:in `instrument'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract_adapter.rb:604:in `log'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:614:in `exec_no_cache'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `execute_and_clear'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:79:in `exec_query'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:371:in `select'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:42:in `select_all'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `block in select_all'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'", "/Users/raphael/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `cache_sql'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/querying.rb:39:in `find_by_sql'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation.rb:678:in `exec_queries'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation.rb:546:in `load'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation.rb:255:in `records'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation.rb:251:in `to_a'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation/finder_methods.rb:536:in `find_nth_with_limit'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation/finder_methods.rb:521:in `find_nth'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/relation/finder_methods.rb:122:in `first'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:17:in `get'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/devise-4.4.1/lib/devise/models/authenticatable.rb:231:in `serialize_from_session'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/devise-4.4.1/lib/devise.rb:480:in `block (2 levels) in configure_warden!'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/session_serializer.rb:35:in `fetch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/proxy.rb:213:in `user'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/proxy.rb:323:in `_perform_authentication'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/proxy.rb:128:in `authenticate!'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/devise-4.4.1/lib/devise/controllers/helpers.rb:118:in `authenticate_admin_user!'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.2.1/lib/active_admin/base_controller.rb:39:in `authenticate_active_admin_user'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:413:in `block in make_lambda'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:198:in `block in halting'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `block in invoke_before'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `each'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:507:in `invoke_before'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:130:in `run_callbacks'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal/rescue.rb:20:in `process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `block in instrument'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `instrument'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/railties/controller_runtime.rb:22:in `process_action'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/abstract_controller/base.rb:124:in `process'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.5/lib/action_view/rendering.rb:30:in `process'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal.rb:189:in `dispatch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal.rb:251:in `block in dispatch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/cookies.rb:613:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_controller/metal.rb:251:in `dispatch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:31:in `serve'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:33:in `each'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:33:in `serve'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:844:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/olive_branch-2.1.2/lib/olive_branch/middleware.rb:58:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/conditional_get.rb:25:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.5/lib/active_record/migration.rb:556:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:97:in `run_callbacks'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/callbacks.rb:24:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/executor.rb:12:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:84:in `protected_app_call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:79:in `better_errors_call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/better_errors-2.4.0/lib/better_errors/middleware.rb:57:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/rack/logger.rb:36:in `call_app'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:21:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/request_id.rb:25:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/executor.rb:12:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.5/lib/action_dispatch/middleware/static.rb:125:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/railties-5.1.5/lib/rails/engine.rb:522:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/puma-3.11.2/lib/puma/configuration.rb:225:in `call'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/puma-3.11.2/lib/puma/server.rb:624:in `handle_request'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/puma-3.11.2/lib/puma/server.rb:438:in `process_client'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/puma-3.11.2/lib/puma/server.rb:302:in `block in run'", "/Users/raphael/.rvm/gems/ruby-2.4.1/gems/puma-3.11.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"]
```

I am providing you the stacktrace as outputed in logs (by the way, is there a way to output the stacktrace in semantic_logger in a more helpful format ? ).

**Comment by shaneog** [comment]
Also having the same issue. 

- Rails 5.1.5
- Ruby 2.5.0
- rails_semantic_logger 4.2.0

**Comment by shaneog** [comment]
Ping @reidmorrison since the issue is closed and could be missed.

**Comment by duckworth** [comment]
Same issue here upgrading to Rails 5.1.5 from 5.0.6 and this is showing up. Ruby 2.4.3 and rails_semantic_logger 4.2.0.
