### ISSUE TITLE
Bug on 

### ISSUE THREAD

**Issue by fanantoxa** [rocketjob/semantic_logger#77]
### Environment

ruby 2.3.1
Puma, Rails
Rails Semantic Logger Version: last
No additional rails configuration

### Bug in the code,
I'm getting next issue:

```
 #<ArgumentError: wrong number of arguments (given 1, expected 0)>
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/log.rb:68:in `assign'
/usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/log.rb:136:in `assign_positional'
```

This issue on current master and last released version (didn't check older versions): 
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/log.rb#L147

```ruby
def assign_positional(message = nil, payload = nil, exception = nil)
...
elsif message.nil? && result.is_a?(Hash)
          assign(result)   # line:147
...
end
```

But actually it can't since method `assign` accept only hash like arguments:

```ruby
def assign(message: nil,
               payload: nil,
               min_duration: 0.0,
               exception: nil,
               metric: nil,
               metric_amount: nil,
               duration: nil,
               backtrace: nil,
               log_exception: :full,
               on_exception_level: nil)
```

## Possible bug
In passed Hash you should have all keys as Symbol type. Any other will be filtered just as usual argument

**Comment by reidmorrison** [comment]
Without the actual code, I am going to guess the logging code looks something like:

```ruby
Rails.logger.info { {'message' => 'blah'} }
```

As of Semantic Logger v4 it needs to be:

```ruby
Rails.logger.info { {message: 'blah'} }
```

Or maybe you want the Hash returned from the Block/Proc to be saved as the payload, which in v4 is now:

```ruby
Rails.logger.info { {payload: { user: 'name' }} }
```

As of v4 the `:payload` is now a child to prevent namespace conflicts between builtin keys and user defined keys. As requested in https://github.com/rocketjob/semantic_logger/issues/35

What does your log line look like, or do you have a reproducible example?

**Comment by fanantoxa** [comment]
@reidmorrison Not sure where it come from, but I have error log:
```
app  | #<ArgumentError: wrong number of arguments (given 1, expected 0)>
app  | /usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/log.rb:68:in `assign'
app  | /usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/log.rb:136:in `assign_positional'
app  | /usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/base.rb:307:in `log_internal'
app  | /usr/local/bundle/gems/semantic_logger-4.1.1/lib/semantic_logger/base.rb:84:in `debug'
app  | /usr/local/bundle/gems/meta_request-0.4.3/lib/meta_request/log_interceptor.rb:8:in `debug'
app  | /usr/local/bundle/gems/rack-cors-0.4.1/lib/rack/cors.rb:116:in `debug'
app  | /usr/local/bundle/gems/rack-cors-0.4.1/lib/rack/cors.rb:85:in `call'
app  | /usr/local/bundle/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
app  | /usr/local/bundle/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
app  | /usr/local/bundle/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
app  | /usr/local/bundle/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
app  | /usr/local/bundle/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
app  | /usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
app  | /usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
app  | /usr/local/bundle/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
app  | /usr/local/bundle/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I'll try to investigate it more. But for now that's all that I have

**Comment by fanantoxa** [comment]
@reidmorrison SO I've got values that actually make this error:
```
app | {:message=>"Started", :payload=>{:method=>"GET", :path=>"/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf", :ip=>"X.X.X.X"}}
app  | ****************************************************************************
app  | ****************************************************************************
app  | {"Access-Control-Allow-Origin"=>"http://localhost:3000", "Access-Control-Allow-Methods"=>"GET, POST, DELETE, PUT, PATCH, OPTIONS, HEAD", "Access-Control-Expose-Headers"=>"", "Access-Control-Max-Age"=>"0", "Access-Control-Allow-Credentials"=>"true"}
app  | ****************************************************************************
```
But not sure for now where it comes from

**Comment by fanantoxa** [comment]
@reidmorrison I think it comes from here:
https://github.com/cyu/rack-cors/blob/v0.4.1/lib/rack/cors.rb#L85

**Comment by fanantoxa** [comment]
@reidmorrison 
On semantic logger (log.rb) we have:
```
 if block_given? && (result = yield)
```
And 
On rack-cors pass here:
```
debug(env) do
          add_headers.each_pair do |key, value|
            if headers.has_key?(key)
              headers["X-Rack-CORS-Original-#{key}"] = value
            end
          end
        end
```
SO As I understand it just pass here a Hash, but with string keys.

I'm sure where is the bug. In logger or rack-cors. What do you think about it?

**Comment by reidmorrison** [comment]
I made the following change to try to handle scenarios like this:
~~~ruby
          # Check if someone just logged a hash payload instead of meaning to call semantic logger
          if message.has_key?(:message) || message.has_key?(:payload) || message.has_key?(:exception) || message.has_key?(:metric)
            log.assign(message)
          else
            log.assign_positional(nil, message, nil, &block)
          end
~~~

It is in master where a lot of work is being done to seamlessly handle Metrics, so it may be a while before v4.2 is officially released. In the meantime `master` "should" work.

Please re-open this ticket if it does not help.

**Comment by fanantoxa** [comment]
@reidmorrison Hi. How to reopen this bug? still happening.
Problem a bit different:
So CORS gem doing next:
They call `debug` with a block
```
debug(env) do
  add_headers.each_pair do |key, value|
    if headers.has_key?(key)
      headers["X-Rack-CORS-Original-#{key}"] = value
    end
  end
end
```
And this code return the `Hash` but with a `String` keys (Usual header pairs)
So this block go through `log_internal` to https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/log.rb#L148

And here it doing:
```
if block_given? && (result = yield)
  if result.is_a?(String)
    message = message.nil? ? result : "#{message} -- #{result}"
    assign(message: message, payload: payload, exception: exception)
  elsif message.nil? && result.is_a?(Hash)
    assign(result)
```
So here the `message` is `nil` and result is a `Hash`
But `Hash` with string keys.
So it call `assign(result)`
Which accept only symbol keys:
```
def assign(message: nil,
               payload: nil,
               min_duration: 0.0,
               exception: nil,
               metric: nil,
               metric_amount: nil,
               duration: nil,
               backtrace: nil,
               log_exception: :full,
               on_exception_level: nil,
               dimensions: nil)
```
So I'm getting 
```
#<ArgumentError: wrong number of arguments (given 1, expected 0)>
/app/vendor/bundle/ruby/2.3.0/gems/semantic_logger-4.2.0/lib/semantic_logger/log.rb:71:in `assign'
```
