### ISSUE TITLE
EOFError exception when using HTTP appender

### ISSUE THREAD

**Issue by betabandido** [rocketjob/semantic_logger#92]
### Environment

Ruby version: 2.1.6p336 (i386-mingw32)
Semantic Logger version: 4.2.0
OS: Windows Server 2008

### Expected Behavior

The following snippet uses the Amazon AWS SDK for Ruby to create an S3 client. As no credentials are specified, creating the client will fail, and a HTTP POST request with the error message should be sent to a test server accepting POST requests.

```ruby
require 'aws-sdk'
require 'semantic_logger'

Aws.use_bundled_cert!

SemanticLogger.add_appender(io: $stdout)
SemanticLogger.add_appender(
	appender: :http,
	url: 'https://httpbin.org/post',
	ssl: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
)
logger = SemanticLogger['Test']

begin
  client = Aws::S3::Client.new
rescue Exception => e
  logger.error(e)
ensure
  SemanticLogger.flush
end
```

Gemfile:

```ruby
source 'https://rubygems.org' do
  gem 'aws-sdk', '~> 3'
  gem 'semantic_logger'
end
```

### Actual Behavior

Semantic logger fails with the following error:

```
2017-12-22 08:57:43.000240 E [2460:SemanticLogger::Processor] SemanticLogger::Processor -- Appender thread: Failed to log to appender: #<SemanticLogger::Appender::Http:0x37ccfe0 @url="https://httpbin.
org/post", @ssl_options={:verify_mode=>0, :use_ssl=>true}, @username=nil, @password=nil, @compress=false, @open_timeout=2.0, @read_timeout=1.0, @continue_timeout=1.0, @header={"Accept"=>"application/j
son", "Content-Type"=>"application/json", "Connection"=>"keep-alive", "Keep-Alive"=>"300"}, @server="httpbin.org", @port=443, @path="/post", @http=#<Net::HTTP httpbin.org:443 open=true>, @formatter=#<
SemanticLogger::Formatters::Json:0x383d600 @time_key=:timestamp, @time_format=:iso_8601, @log_host=true, @log_application=true, @hash={:host=>"channeljobs103", :application=>"Semantic Logger", :timest
amp=>"2017-12-22T13:57:42.989239Z", :level=>:error, :level_index=>4, :pid=>2460, :thread=>"20292060", :file=>"./test.rb", :line=>17, :name=>"Test", :exception=>{:name=>"NoMethodError", :message=>"unde
fined method `match' for nil:NilClass", :stack_trace=>["C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:82:in `block in partition_matching_region'", "C
:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:81:in `each'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_pro
vider.rb:81:in `find'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:81:in `partition_matching_region'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-pa
rtitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:70:in `get_partition'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:23:in `signing_region'
", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-partitions-1.51.0/lib/aws-partitions/endpoint_provider.rb:99:in `signing_region'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/plugin
s/s3_signer.rb:20:in `block in <class:S3Signer>'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:70:in `call'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-s
dk-core-3.12.0/lib/seahorse/client/configuration.rb:70:in `call'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'", "C:
/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:57:in `each'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:57
:in `each'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahor
se/client/configuration.rb:200:in `value_at'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:189:in `block in resolve'", "C:/Ruby21/lib/ruby/2.1.0/set.rb
:263:in `each_key'", "C:/Ruby21/lib/ruby/2.1.0/set.rb:263:in `each'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:189:in `resolve'", "C:/Ruby21/lib/rub
y/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:177:in `apply_defaults'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/configuration.rb:150:in
 `build!'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/base.rb:62:in `build_config'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/base.
rb:19:in `initialize'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-s3-1.8.0/lib/aws-sdk-s3/client.rb:197:in `initialize'", "C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/
base.rb:99:in `new'", "./test.rb:15:in `<main>'"]}}, @log=#<SemanticLogger::Log:0x4a9f808 @level=:error, @thread_name="20292060", @name="Test", @time=2017-12-22 13:57:42 UTC, @tags=[], @named_tags={},
 @level_index=4, @message=nil, @payload=nil, @exception=#<NoMethodError: undefined method `match' for nil:NilClass>, @backtrace=["./test.rb:17:in `rescue in <main>'", "./test.rb:20:in `<main>'"]>, @lo
gger=#<SemanticLogger::Appender::Http:0x37ccfe0 ...>>, @application=nil, @host=nil, @filter=nil, @name="SemanticLogger::Appender::Http", @level_index=nil, @level=nil, @logger=#<SemanticLogger::Appende
r::File:0x4a9e398 @log=#<IO:<STDERR>>, @formatter=#<SemanticLogger::Formatters::Default:0x37ea830 @time_format="%Y-%m-%d %H:%M:%S.%6N", @log_host=true, @log_application=true>, @application=nil, @host=
nil, @filter=nil, @name="SemanticLogger::Appender::Http", @level_index=3, @level=:warn>> -- Exception: EOFError: end of file reached
C:/Ruby21/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
C:/Ruby21/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
C:/Ruby21/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
C:/Ruby21/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
C:/Ruby21/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/net_http/patches.rb:30:in `block in new_transport_request'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/net_http/patches.rb:27:in `catch'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/aws-sdk-core-3.12.0/lib/seahorse/client/net_http/patches.rb:27:in `new_transport_request'
C:/Ruby21/lib/ruby/2.1.0/net/http.rb:1384:in `request'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/http.rb:208:in `process_request'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/http.rb:187:in `post'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/http.rb:166:in `log'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/processor.rb:97:in `block in log'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/processor.rb:95:in `each'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/processor.rb:95:in `log'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/async.rb:123:in `process_messages'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/async.rb:104:in `process'
C:/Ruby21/lib/ruby/gems/2.1.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/async.rb:70:in `block in thread'
```

This error only seems to happen when using the Amazon AWS SDK. After some digging, this might be related to the fact that Amazon patches Net::HTTP library (see https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/seahorse/client/net_http/patches.rb).

There are reports of similar errors in multiple forums, so it seems it is not a very unusual problem. We have effectively managed to solve the issue by creating a subclass of the `Http` adapter:

```ruby
  class HttpAppender < SemanticLogger::Appender::Http
    def log(log)
      retries ||= 0
      message = formatter.call(log, self)
      logger.trace(message)
      post(message)
    rescue EOFError => e
      retry if (retries += 1) < 3
      raise e
    end
  end
```

We have seen that retrying once seems to always succeed. But, we are not experts on the internals of Net::HTTP, so we would like to have your feedback on this. And, hopefully implement the fix in `semantic_logger` itself, so that we do not need to inherit from the `Http` adapter.

**Comment by workgena** [comment]
Can it be related to problem I've trapped with [Unicorn workers](https://github.com/rocketjob/rails_semantic_logger/issues/52)?

**Comment by reidmorrison** [comment]
It looks like Net::HTTP in Ruby 2.5 has built-in support for retries. In the meantime there is nothing wrong with the solution above.
