### ISSUE TITLE
semantic_logger/appender/async.rb:80: [BUG] pthread_mutex_lock: Invalid argument (EINVAL)

### ISSUE THREAD

**Issue by d4be4st** [rocketjob/semantic_logger#94]
### Environment

Provide at least:
* Ruby Version. 2.5.0
* Semantic Logger Version. 4.2.0
* Rails 5.1.4
* Rails Semantic Logger Version, 4.2.0
* Phusion Passenger Enterprise: 5.1.11
* Rails configuration.
```
  SemanticLogger.add_appender(
    appender:    :graylog,
    url:         Rails.application.secrets.graylog_host,
    application: "flowstate-#{Rails.env}",
    level:       :debug,
    gelf_options: {
      tls: {
        cert: '/etc/ssl/private/graylog/graylog.crt',
        key: '/etc/ssl/private/graylog/graylog.key'
      }
    }
  )
```

* Full Stack Trace, if an exception is being raised.
Had to get this from nginx error log
```
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:97:in `block in create_thread_and_abort_on_exception'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:440:in `block (3 levels) in start_threads'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:98:in `main_loop'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:137:in `accept_and_process_next_request'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `process_request'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:367:in `maybe_tag_logger'
App 30257 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:81:in `block in process_request'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/ssl.rb:66:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:19:in `call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/base.rb:190:in `tagged'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/semantic_logger.rb:299:in `fast_tag'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/rails/rack/logger.rb:19:in `block in call'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:35:in `call_app'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/rails_semantic_logger-4.2.0/lib/rails_semantic_logger/extensions/rails/rack/logger_info_as_debug.rb:15:in `info'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/base.rb:84:in `debug'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/base.rb:330:in `log_internal'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/logger.rb:38:in `log'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/processor.rb:38:in `<<'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/async.rb:80:in `log'
App 30257 stderr: /home/fs_api_stag/www/fs-api-stag.byinfinum.co/shared/vendor/bundle/ruby/2.5.0/gems/semantic_logger-4.2.0/lib/semantic_logger/appender/async.rb:80:in `push'
```

The problem occurs on a ec2 server running ubuntu distro. Do not know if it is a problem with passenger or with semantic logger. 

Ran it locally (on macos) with the same passenger version, and it works just fine :(

**Comment by d4be4st** [comment]
Downgraded the ruby version to 2.4 and now it works.

Seems like there is an issue with ruby 2.5 Queues and phusion passenger.
